# Travis CI configuration file.

language: php

# Run against all versions of PHP supported by WordPress.
php:
    - 7.2
    - 7.1
    - 7.0
    - 5.6
    - 5.5
    - 5.4

# Run against last few versions of WordPress.
env:
    - WP_VERSION=4.8
    - WP_VERSION=4.7
    - WP_VERSION=4.6

# Use the faster container-based builds.
sudo: false

matrix:
    # Run against HHVM and PHP nightly only with the latest version of WordPress.
    include:
        - php: 5.2
          env: WP_VERSION=4.8
          dist: precise
        - php: 5.3
          env: WP_VERSION=4.8
          dist: precise
        - php: hhvm
          env: WP_VERSION=4.8
        - php: nightly
          env: WP_VERSION=4.8
    # These are experimental, so allow for failures without failing the whole build.
    allow_failures:
        - php: hhvm
        - php: nightly
    # Let us know as soon as something has exploded.
    fast_finish: true

before_script:
    # Set up the WordPress directory.
    - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
    - mkdir -p /tmp/wordpress/src/wp-admin/includes
    - mkdir -p /tmp/wordpress/src/wp-includes
    # Download the base filesystem class.
    - wget -O /tmp/wordpress/src/wp-admin/includes/class-wp-filesystem-base.php http://develop.svn.wordpress.org/branches/$WP_VERSION/src/wp-admin/includes/class-wp-filesystem-base.php
    # Download the WP_Error class, it is a dependency of the filesystem classes.
    - wget -O /tmp/wordpress/src/wp-includes/class-wp-error.php http://develop.svn.wordpress.org/branches/$WP_VERSION/src/wp-includes/class-wp-error.php

script:
    - phpunit
